-- init schema

CREATE TYPE user_role AS ENUM ('mahasiswa', 'dosen', 'staff', 'admin', 'teknisi', 'superadmin');

CREATE TABLE users (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  nama TEXT NOT NULL,
  identitas TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  no_hp TEXT,
  role user_role DEFAULT 'mahasiswa',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE kategori (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kategori TEXT NOT NULL
);

CREATE TABLE lokasi (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_lokasi TEXT NOT NULL,
  detail_lokasi TEXT
);

CREATE TYPE damage_level AS ENUM ('ringan', 'sedang', 'berat', 'darurat');
CREATE TYPE report_status AS ENUM ('menunggu_verifikasi', 'diverifikasi', 'ditolak', 'diproses', 'selesai');

CREATE TABLE laporan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_user UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  id_kategori BIGINT NOT NULL REFERENCES kategori(id),
  id_lokasi BIGINT NOT NULL REFERENCES lokasi(id),
  judul TEXT NOT NULL,
  deskripsi TEXT NOT NULL,
  tingkat_kerusakan damage_level DEFAULT 'ringan',
  foto_kerusakan TEXT, 
  status report_status DEFAULT 'menunggu_verifikasi',
  catatan_admin TEXT,
  assigned_to UUID REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE bukti_perbaikan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_laporan BIGINT NOT NULL REFERENCES laporan(id) ON DELETE CASCADE,
  id_teknisi UUID NOT NULL REFERENCES users(id),
  foto_selesai TEXT,
  catatan_teknisi TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
